export { default as Footer } from "../components/footer/Footer"
export { default as Search } from "../components/search/Search"
export { default as HistoryNotFound } from "../components/history/History-notfound"
export { default as History } from "../components/history/History"
export { default as Profile } from "../components/profile/Profile"
export { default as Tarif } from "../components/tarif/Tarif"
export { default as Subscription } from "../components/subscription/Subscription"
export { default as Chat } from "../components/chat/Chat"
export { default as Layout } from "../components/layout/Layout"
export { default as Favorites } from "../components/favorites/Favorites"
export { default as Header } from "../components/header/Header"
export { default as ChatList } from "../components/chat-list/Chat-list"
export { default as Questionnaire } from "../components/questionnaire/Questionnaire"
export { default as Register } from "../components/register/Register"
export { default as Gost } from "../components/gost/Gost"
export {default as Mutually} from "../components/mutually/Mutually"